"use client";

import type React from "react";

import localFont from "next/font/local";
import "./globals.css";
import Container from "@/components/layout/container";
import ToggleRoleButton from "@/features/auth/components/toggle-role-button";
import { useRole } from "@/features/auth/hooks/use-role-hooks";
import { Role } from "@/types/role";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  company,
  user,
  modal,
}: Readonly<{
  children: React.ReactNode;
  company: React.ReactNode;
  user: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const role = useRole((state) => state.role);

  const route = (role: Role) => {
    switch (role) {
      case Role.Company:
        return company;
      case Role.User:
        return user;
      case Role.Admin:
        return null;
    }
  };

  const main = route(role);

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <div>{children}</div>
        <div>{main}</div>
        <div>{modal}</div>
        <div className="fixed bottom-36 inset-x-0">
          <Container className="flex justify-end">
            <ToggleRoleButton />
          </Container>
        </div>
      </body>
    </html>
  );
}
